added support for script arguments (fixes #18)

diff --git a/kscript b/kscript
--- a/kscript
+++ b/kscript
@@ -7,6 +7,7 @@ assertInPath(){ if [ -z "$(which $1)" ]; then echo "[ERROR] Could not locate '$1
 
 assertInPath kotlinc
 assertInPath mvn
+assertInPath curl
 
 ## prefer JAVA_HOME over PATH for javac and jar (to stay in sync with kotlinc; see  #6)
 if [ -n "$JAVA_HOME" -a -x "$JAVA_HOME/bin/java" ]; then
@@ -46,7 +47,7 @@ fi
 ## optionally clear up the jar cache
 if [ "$1" == "--clear-cache" ]; then
     echo "Cleaning up cache..."
-    rm -f ${TMPDIR=/tmp}/.kscript_*
+    rm -f ${TMPDIR=/tmp}/kscript_*
     exit 0
 fi
 
@@ -78,11 +79,6 @@ shift
 if [ "${OSTYPE//[0-9.]/}" == "darwin" ]; then md5sum(){ md5 -r $1; }; fi
 
 
-## If script is provided from stdin create a temporary file
-## note we cannot  support empty args list here because this would confuse with actual script args
-if [ "$scriptFile" == "-" ]; then scriptFile="/dev/stdin"; fi
-
-#if [ "$scriptFile"=="/dev/stdin" ]; then
 
 ## Support URLs as script files
 ## http://stackoverflow.com/questions/2172352/in-bash-how-can-i-check-if-a-string-begins-with-some-value
@@ -90,32 +86,58 @@ if [[ "$scriptFile" == "http://"* ]] || [[ "$scriptFile" == "https://"* ]]; then
     urlHash=$(echo "$scriptFile" | md5sum)
 
     # http://unix.stackexchange.com/questions/174817/finding-the-correct-tmp-dir-on-multiple-platforms
-    tmpScript=${TMPDIR=/tmp}/.kscript_urlkts_cache_${urlHash}.kts
+    urlCache=${TMPDIR=/tmp}/kscript_urlkts_cache_${urlHash}.kts
 
-    if [ ! -f "$tmpScript" ]; then
+    if [ ! -f "$urlCache" ]; then
 #        echo "fetching kscript from url $scriptFile into ${tmpScript}..."
-        curl -L ${scriptFile} 2>/dev/null > ${tmpScript}
+        curl -L ${scriptFile} 2>/dev/null > ${urlCache}
     fi
 
-    scriptFile=${tmpScript}
+    scriptFile=${urlCache}
 fi
 
-## Rather Test if script ends with kts to also support process substitution here. Wrap stdin
+
+
+
+## remap - to the standard input file-descriptor
+if [ "$scriptFile" == "-" ]; then scriptFile="/dev/stdin"; fi
+
+
+## if scriptFile is still not a file we assume the input to be a kotlin program directly
+## note: -e also supports non-regular files in contrast to -f
+if [[ ! -e ${scriptFile} ]] && [[ "$scriptFile" != *kts ]]; then
+#    echo "processing direct script argument"
+    urlHash=$(echo "$scriptFile" | md5sum)
+
+    # http://unix.stackexchange.com/questions/174817/finding-the-correct-tmp-dir-on-multiple-platforms
+    urlCache=${TMPDIR=/tmp}/kscript_scriptarg_cache_${urlHash}.kts
+
+    echo "$scriptFile" > $urlCache
+
+    scriptFile=${urlCache}
+fi
+
+
+## Support for support process substitution and stdin.
 # http://serverfault.com/questions/52034/what-is-the-difference-between-double-and-single-square-brackets-in-bash
 # https://viewsby.wordpress.com/2013/09/06/bash-string-ends-with/
-
 if [[ "$scriptFile" != *kts ]]; then
-    tmpScript=${TMPDIR=/tmp}/.kscript_stdin_${RANDOM}${RANDOM}.kts # odd but works on macos as well
-    cat "${scriptFile}" > ${tmpScript}
+    urlCache=${TMPDIR=/tmp}/kscript_stdinbuffer_${RANDOM}${RANDOM}.kts # odd but works on macos as well
+    cat "${scriptFile}" > ${urlCache}
 
     ## rename to use checksum as name to allow for jar-caching also when using stdin
-    stdinMD5=$(md5sum ${tmpScript} | cut -c1-6)
+    stdinMD5=$(md5sum ${urlCache} | cut -c1-6)
 
     ## replace script file with md5 hash file copy of stdin
-    scriptFile=$(dirname ${tmpScript})/kscript_stdin_${stdinMD5}.kts
-    mv ${tmpScript} $scriptFile
+    scriptFile=$(dirname ${urlCache})/kscript_stdin_${stdinMD5}.kts
+    mv ${urlCache} $scriptFile
 fi
 
+## just proceed if the script file is a regular file at this point
+if [[ ! -f $scriptFile ]]; then
+    echo "[ERROR] Could not open script file '$scriptFile'" 1>&2
+    exit 1
+fi
 
 
 ### auto-install expandcp.kts into same dir as kscript for automatic dependency resolution if not yet in PATH
@@ -124,6 +146,7 @@ if ! which expandcp.kts &> /dev/null; then
     curl -s https://raw.githubusercontent.com/holgerbrandl/kscript/master/expandcp.kts > ${installDir}/expandcp.kts
     chmod u+x ${installDir}/expandcp.kts
 fi
+
 
 ## Extract dependencies from script
 #scriptFile=/Users/brandl/projects/kotlin/kscript/test/resources/multi_line_deps.kts
@@ -135,9 +158,10 @@ dependencies=$(grep "^//DEPS" ${scriptFile} | cut -f2- -d' ' | trim | tr ',;\n' 
 
 
 ## First try dependency cache directly to avoid jvm launch for expandcp.kts
-dependency_cache="/tmp/.kscript_deps_cache.txt"
+# fix me more consistent use of ${TMPDIR}
+dependency_cache="/tmp/kscript_deps_cache.txt"
 if [ -n "$dependencies" ] && [ -f "$dependency_cache" ]; then
-    classpath=$(grep -F $(echo ${dependencies} | tr ' ' ';')" " /tmp/.kscript_deps_cache.txt | cut -d' ' -f2)
+    classpath=$(grep -F $(echo ${dependencies} | tr ' ' ';')" " /tmp/kscript_deps_cache.txt | cut -d' ' -f2)
 fi
 
 ## If there are dependencies but cache-lookup failed we run expandcp.kts
@@ -178,6 +202,7 @@ className=$(basename ${scriptFile} .kts)
 className=$(echo ${className:0:1} | tr  '[a-z]' '[A-Z]')${className:1}
 
 
+#ls -la  ${jarFile}
 # build cache-jar if it does not yet exist
 if [ ! -f "${jarFile}" ]; then
     ## remove previous (now outdated) cache jars
@@ -191,7 +216,7 @@ if [ ! -f "${jarFile}" ]; then
     fi
 
 
-    # fixme xxxx placeholder does not work on macos
+    # note xxxx placeholder does not work on macos but mktemp creates unique path alreade
     mainJava=$(mktemp -dt kscript.XXXXXX)/Main_${className}.java
 
     echo '
