added support for .kt files via //ENTRY directive (fixes #31)

diff --git a/kscript b/kscript
--- a/kscript
+++ b/kscript
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 ## note: always use a patch release even if it's 0
-KSCRIPT_VERSION=1.5.3
+KSCRIPT_VERSION=1.5.4-SNAPSHOT
 
 ## make sure that all requirements (java, kotlinc, maven) to run kscript are met
 assertInPath(){ if [ -z "$(which $1)" ]; then echo "[ERROR] Could not locate '$1'" 1>&2; exit 1; fi }
@@ -65,6 +65,7 @@ if [ $# == 0 ]  || [ "$1" == "-v" ] || [ "$1" == "--version" ] || [ "$1" == "-h"
     exit 0;
 fi
 
+## later" custom cache directories? see https://github.com/holgerbrandl/kscript/issues/5
 #KSCRIPT_CACHE_DIR=${TMPDIR=/tmp}
 KSCRIPT_CACHE_DIR=${HOME}/.kscript
 
@@ -160,7 +161,7 @@ if [ "$scriptFile" == "-" ]; then scriptFile="/dev/stdin"; fi
 ## Support for support process substitution and stdin.
 # http://serverfault.com/questions/52034/what-is-the-difference-between-double-and-single-square-brackets-in-bash
 # https://viewsby.wordpress.com/2013/09/06/bash-string-ends-with/
-if [[ "$scriptFile" != *kts ]] && [[ -e ${scriptFile} ]] ; then
+if [[ "$scriptFile" != *kts ]] && [[ "$scriptFile" != *kt ]] && [[ -e ${scriptFile} ]] ; then
     stdinCache=${KSCRIPT_CACHE_DIR}/stdinbuffer_${RANDOM}${RANDOM}.kts # odd but works on macos as well
     cat "${scriptFile}" > ${stdinCache}
 
@@ -203,9 +204,8 @@ if [[ ! -f ${scriptFile} ]]; then
 fi
 
 
-
 ## Extract dependencies from script
-#scriptFile=/Users/brandl/projects/kotlin/kscript/test/resources/multi_line_deps.kts
+# kscript /Users/brandl/projects/kotlin/kotlin_playground/src/test_hello.kt
 if [ $(grep "^// DEPS" ${scriptFile} | wc -l) -gt 0 ]; then
     echo "[ERROR] Dependencies must be declared by using the line prefix //DEPS" 1>&2; exit 1;
 fi
@@ -236,6 +236,8 @@ if [ "$is_interactive" = true ]; then
     exec kotlinc ${kotlin_opts} -classpath "${classpath}"
 fi
 
+#echo "script file is $scriptFile"
+scriptFileExt=".${scriptFile##*.}"
 scriptCheckSum=$(kscript_md5 ${scriptFile})
 
 ## we can use readlink here which is not functional on macos, thus:
@@ -246,49 +248,89 @@ scriptCheckSum=$(kscript_md5 ${scriptFile})
 #    echo "$(readlink ${minusFarg} $1)";
 #}
 
-# see https://github.com/holgerbrandl/kscript/issues/5
-#jarDir=$(dirname $(abspath  ${scriptFile}))
+
+## Even if we just need and support the//ENTRY directive in case of kt-class files, we extract
+## it here to fail if it was used in kts files.
+entryDirective=$(grep "^//ENTRY" ${scriptFile} | cut -f2- -d' ' | trim)
+if [[ -n "${entryDirective}" ]] && [[ ${scriptFileExt} == ".kts" ]] ; then
+    echo "ERROR: //ENTRY directive is just supported for kt class files" >&2
+    exit 1;
+fi
+
+
+#https://stackoverflow.com/questions/965053/extract-filename-and-extension-in-bash
 jarFile=${KSCRIPT_CACHE_DIR}/$(basename ${scriptFile} .kts).${scriptCheckSum}.jar
 
 
 ## capitalize first letter and get rid of dashes (since this is what kotlin compiler is doing for the wrapper to create a valid java class name)
-className=$(basename ${scriptFile} .kts | tr '-' '_')
+className=$(basename ${scriptFile} ${scriptFileExt} | tr '-' '_' | tr '.' '_')
 #className="${className^}" ## disabled because requires bash4 and thus not on macos
 className=$(echo ${className:0:1} | tr  '[a-z]' '[A-Z]')${className:1}
 
 
-#ls -la  ${jarFile}
+
+if [[ $scriptFileExt == ".kts" ]]; then
+    execClassName=Main_${className}
+
+elif [[ $scriptFileExt == ".kt" ]]; then
+#    entryDirective=$(grep "^//ENTRY" ${scriptFile} | cut -f2- -d' ' | trim)
+
+     # use default entry directive if not defined
+    if [[ -z "$entryDirective" ]]; then
+        entryDirective="${className}Kt"
+    else
+        entryDirective=${entryDirective}
+    fi
+
+    package=$(grep "^package" ${scriptFile} | cut -f2- -d' ')"."
+    package=$(echo ${package} | sed 's/^.$//g')
+
+    execClassName="${package}${entryDirective}"
+fi
+
+
+echo "classpath is '${classpath}'"
+
+
 # build cache-jar if it does not yet exist
 if [ ! -f "${jarFile}" ]; then
     ## remove previous (now outdated) cache jars
     rm -f .$(basename ${scriptFile} .kts).*.jar
 
+
+    echo "kotlinc  -classpath "${classpath}" -d ${jarFile} ${scriptFile}"
     kotlinc  -classpath "${classpath}" -d ${jarFile} ${scriptFile}
 
     if [ $? -eq 1 ]; then
-        echo "ERROR: compilation of '$scriptFile' failed" >&2
+        echo "[ERROR] compilation of '$scriptFile' failed" >&2
         exit 1;
     fi
 
+    if [[ $scriptFileExt == ".kts" ]]; then
+        execClassName=Main_${className}
 
-    # note xxxx placeholder does not work on macos but mktemp creates unique path alreade
-    mainJava=$(mktemp -dt kscript.XXXXXX)/Main_${className}.java
+        # note xxxx placeholder does not work on macos but mktemp creates unique path alreade
+        mainJava=$(mktemp -dt kscript.XXXXXX)/${execClassName}.java
 
-    echo '
-    public class Main_'${className}' {
-        public static void main(String... args) throws Exception {
-            Class script = Main_'${className}'.class.getClassLoader().loadClass("'${className}'");
-            script.getDeclaredConstructor(String[].class).newInstance((Object)args);
+        echo '
+        public class Main_'${className}' {
+            public static void main(String... args) throws Exception {
+                Class script = Main_'${className}'.class.getClassLoader().loadClass("'${className}'");
+                script.getDeclaredConstructor(String[].class).newInstance((Object)args);
+            }
         }
-    }
-    '> ${mainJava}
+        '> ${mainJava}
 
+        ${JAVAC_CMD:=javac} ${mainJava}  2> /dev/null
 
-    ${JAVAC_CMD:=javac} ${mainJava}  2> /dev/null
-
-    ## update the jar to include main-wrapper
-    (cd $(dirname ${mainJava}) && ${JAR_CMD:=jar} uf ${jarFile} $(basename ${mainJava%%.java}.class))
+        ## update the jar to include main-wrapper
+        (cd $(dirname ${mainJava}) && ${JAR_CMD:=jar} uf ${jarFile} $(basename ${mainJava%%.java}.class))
+    fi
 fi
+
+#echo "genClassName is ${className}"
+#echo "execClassName is ${execClassName}"
+#echo "jar file is ${jarFile}"
 
 
 ## disabled since kotlin binary fails to add kotlin-stdb when using jar as sole argument
@@ -302,7 +344,6 @@ fi
 if [ -z "$KOTLIN_HOME" ]; then
     ## see discussion on https://github.com/holgerbrandl/kscript/issues/15
     KOTLIN_HOME=$(KOTLIN_RUNNER=1 JAVACMD=echo kotlinc | awk 'NR>1' RS=' ' | grep -F kotlin.home= | cut -d= -f2)
-#    ls -la ${KOTLIN_HOME}/lib/kotlin-script-runtime.jar
 fi
 
 ## fail if KOTLIN_HOME is still unknown or does not exist
@@ -314,4 +355,4 @@ fi
 
 # http://stackoverflow.com/questions/3706689/java-class-files-in-current-directory
 # also see https://youtrack.jetbrains.com/issue/KT-17100
-exec kotlin ${kotlin_opts} -classpath ${jarFile}:${KOTLIN_HOME}/lib/kotlin-script-runtime.jar:"$classpath" Main_${className} "$@"
+exec kotlin ${kotlin_opts} -classpath ${jarFile}:${KOTLIN_HOME}/lib/kotlin-script-runtime.jar:"${classpath}" ${execClassName} "$@"
