Small fixes and improvements

diff --git a/src/kscript b/src/kscript
--- a/src/kscript
+++ b/src/kscript
@@ -46,4 +46,12 @@ fi
 export KSCRIPT_FILE="$1"
 
 ## run it using command substitution to have just the user process once kscript is done
-eval "exec $("${KOTLIN_BIN}kotlin" -classpath "${JAR_PATH}" kscript.app.KscriptKt "$OSTYPE" "$@")"
+COMMAND=$("${KOTLIN_BIN}kotlin" -classpath "${JAR_PATH}" kscript.app.KscriptKt "$OSTYPE" "$@")
+RESULT=$?
+
+if [ ! $RESULT -eq 0 ]; then
+    echo "KScript execution failure: $RESULT"
+    exit $RESULT
+fi
+
+eval "exec $COMMAND"
