Kscript 4.2 (#381)
*Breaking changes*

* Renamed environment variable from 'KSCRIPT_DIR' to 'KSCRIPT_DIRECTORY'

*Enhancements*

* New GitHub organization: http://github.com/kscripting[kscripting]
* More work on Windows shell compatibility; most functionality works on Windows as on systems with bash
* Change the name of the kscript package to io.github.kscripting:kscript
* Final execution of the script is handled by kscript, not by bash (reduces dependency on bash)
* Separate library for shell execution kscripting/shell
* Ability to provide local artifacts path through *KSCRIPT_DIRECTORY_ARTIFACTS* or configuration file property:
 *scripting.directory.artifacts* (thanks to https://github.com/vsajip[Vsajip] for initial implementation)
* kscript jar is released to Maven Central: *io.github.kscripting:kscript:4.2.0*
* Change the way of checking the latest kscript version (simplifies releases)
* Deprecate old annotations in the kscript-annotations library
* Improved implementation: VersionChecker, ConfigBuilder etc.
* Updated Gradle and dependencies
* Deprecated @file:Include in favour of @file:Import as a preparation of switch to Kotlin Scripting
* Replaced DocOpt with Apache CLI
* Changed the way of creating distribution package - now it is handled by Gradle
* Version of kscript is set by Gradle (generated BuildConfig class)
* Improved DependencyResolver: aar archives are also included in the classpath
* When creating an IntelliJ project, Gradle and Idea is no more required

*Bugfixes*

* Fixed exit code on Windows

*Other*
* Deprecation of "Include" in favor of "Import"
* Infrastructure for publishing kscript
* Updated kscript-annotations
* Changed a way of building distribution of kscript
* KScript version is derived from Gradle build file (BuildConfig)
* Handle snapshot versions in VersionChecker
* Updated Github actions
* Updated start-up scripts
* Additional tests, which now work on Windows.
* Updated Kotlin version
* Fixed REPL
* Better handling of different command line options
* Build target is now JVM 11
* Documentation converted to .adoc
* Fixed Dockerfile
* Updated docs
* Updated dependencies

diff --git a/src/kscript b/src/kscript
--- a/src/kscript
+++ b/src/kscript
@@ -1,12 +1,14 @@
 #!/usr/bin/env bash
 
-absolute_path() {
+# Based on kotlinc.bat from the Kotlin distribution
+
+resolveAbsolutePath() {
     # if the given path to the kscript launcher is absolute (i.e. it is either starting with / or a
     # 'letter:/' when using gitbash on windows) it is returned unchanged, otherwise we construct an absolute path
     [[ $1 = /* ]] || [[ $1 =~ ^[A-z]:/ ]] && echo "$1" || echo "$PWD/${1#./}"
 }
 
-resolve_symlink() (
+resolveSymlinks() (
     if [[ $OSTYPE != darwin* ]]; then minusFarg="-f"; fi
     sym_resolved=$(readlink ${minusFarg} $1)
 
@@ -17,43 +19,73 @@ resolve_symlink() (
     fi
 )
 
-ABS_KSCRIPT_PATH=$(resolve_symlink $(absolute_path $0))
+findJavaVersion() {
+    # Note that this only loads the first component of the version, so "1.8.0_265" -> "1".
+    # But it's fine because major version is 9 for JDK 9, and so on.
+    regex='^.*version "([[:digit:]]+).*$'
+    while read -r line; do
+        if [[ "$line" =~ $regex ]]; then
+            echo ${BASH_REMATCH[1]}
+        fi
+    done <<< $("${JAVACMD:=java}" -version 2>&1)
+}
 
-JAR_PATH=$(dirname "$ABS_KSCRIPT_PATH")/kscript.jar
+# Resolve KSCRIPT_HOME
+KSCRIPT_HOME=$(dirname $(dirname $(resolveSymlinks $(resolveAbsolutePath $0))))
+KSCRIPT_LIB="$KSCRIPT_HOME/bin"
 
-## prefer KOTLIN_HOME instead of PATH to resolve `kotlin` location (see #145)
-if [[ -z "$KOTLIN_HOME" ]]; then
-  KOTLIN_BIN=""
-
-  # see discussion on https://github.com/holgerbrandl/kscript/issues/15
-  REGEXP="-Dkotlin\.home=([^ ]*)"
-  GUESS_KOTLIN_HOME=$(KOTLIN_RUNNER=1 JAVACMD=echo kotlinc)
-
-  if [[ $GUESS_KOTLIN_HOME =~ $REGEXP ]]; then
-    KOTLIN_BIN="${BASH_REMATCH[1]}/bin/"
-  fi
-else
-  KOTLIN_BIN="$KOTLIN_HOME/bin/"
+# Resolve JAVA_CMD
+if [ -z "$JAVACMD" -a -n "$JAVA_HOME" -a -x "$JAVA_HOME/bin/java" ]; then
+    JAVACMD="$JAVA_HOME/bin/java"
 fi
 
 # OSTYPE can be: linux*, freebsd, darwin*, cygwin, msys
 if [[ "$OSTYPE" == "cygwin" || "$OSTYPE" == "msys" ]]; then
-  JAR_PATH=$(cygpath -w "${JAR_PATH}")
-  KOTLIN_BIN=$(cygpath "${KOTLIN_BIN}")
-  true
+  KSCRIPT_LIB=$(cygpath -w "${KSCRIPT_LIB}")
 fi
 
 ## expose the name of the script being run to the script itself
 export KSCRIPT_FILE="$1"
 
-## run it using command substitution to have just the user process once kscript is done
-COMMAND=$("${KOTLIN_BIN}kotlin" -classpath "${JAR_PATH}" kscript.app.KscriptKt "$OSTYPE" "$@")
-RESULT=$?
+[ -n "$JAVA_OPTS" ] || JAVA_OPTS="-Xmx256M -Xms32M"
 
-if [ ! $RESULT -eq 0 ]; then
-    exit $RESULT
+declare -a JAVA_ARGS
+declare -a KOTLIN_ARGS
+
+while [ $# -gt 0 ]; do
+  case "$1" in
+    -D*)
+      JAVA_ARGS=("${JAVA_ARGS[@]}" "$1")
+      shift
+      ;;
+    -J*)
+      JAVA_ARGS=("${JAVA_ARGS[@]}" "${1:2}")
+      if [ "x${1:2}" = "x" ]; then
+        echo "error: empty -J argument"
+        exit 1
+      fi
+      shift
+      ;;
+    *)
+      KOTLIN_ARGS=("${KOTLIN_ARGS[@]}" "$1")
+      shift
+      ;;
+  esac
+done
+
+# Additional Java args
+JAVA_VERSION="$(findJavaVersion)"
+if [[ $JAVA_VERSION -ge 9 ]]; then
+  # Workaround the illegal reflective access warning from ReflectionUtil to ResourceBundle.setParent, see IDEA-248785.
+  JAVA_ARGS=("${JAVA_ARGS[@]}" "--add-opens" "java.base/java.util=ALL-UNNAMED")
 fi
 
-if [ -n "$COMMAND" ]; then
-    eval "exec $COMMAND"
+if [[ $JAVA_VERSION < 13 ]]; then
+  JAVA_ARGS=("${JAVA_ARGS[@]}" "-noverify")
 fi
+
+# KScript dependencies itself
+CLASS_PATH="$KSCRIPT_LIB/*"
+
+## execute process
+"${JAVACMD:=java}" $JAVA_OPTS "${JAVA_ARGS[@]}" -classpath "$CLASS_PATH" io.github.kscripting.kscript.KscriptKt "$OSTYPE" "${KOTLIN_ARGS[@]}"
